# Generated by Django 5.2.3 on 2025-07-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_backdrop_path_movie_poster_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userrating',
            name='review',
        ),
    ]
